---
namespace: accounts

resources:
  - namespace.yaml
  - configmap.yaml
  - web-deployment.yaml
  - celery-deployment.yaml
  - flower-deployment.yaml
  - service.yaml
  - flower-service.yaml
  - pdb.yaml
  - externalsecret.yaml
  - db-externalsecret.yaml

labels:
  - pairs:
      app: accounts
